name: jawir
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  flutter_launcher_icons: ^0.11.0
  google_fonts: ^6.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Yc.png"

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/

